export const LOAD_SERIALS_SUCCESS = 'LOAD_SERIALS_SUCCESS';
export const LOAD_ONE_SERIAL_SUCCESS = 'LOAD_ONE_SERIAL_SUCCESS';
export const UPDATE_SERIAL_SUCCESS = 'UPDATE_SERIAL_SUCCESS';
export const CREATE_SERIAL_SUCCESS = 'CREATE_SERIAL_SUCCESS';
export const DELETE_SERIAL_SUCCESS = 'DELETE_SERIAL_SUCCESS';

export default LOAD_SERIALS_SUCCESS;
